### ISSUE TITLE
魔趣81.0保存带有自适应图标的未适配应用图标时闪退。

### ISSUE THREAD

**Issue by Butanediol** [by-syk/NanoIconPack#9]
```
FATAL EXCEPTION: main
 Process: com.oblatum.iconpack, PID: 30267
 java.lang.ClassCastException: android.graphics.drawable.AdaptiveIconDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
 	at com.by_syk.lib.nanoiconpack.d.d.a(Unknown Source:12)
 	at com.by_syk.lib.nanoiconpack.c.b.a(Unknown Source:42)
 	at com.by_syk.lib.nanoiconpack.c.b.a(Unknown Source:0)
 	at com.by_syk.lib.nanoiconpack.c.b$2.c(Unknown Source:2)
 	at com.by_syk.lib.nanoiconpack.d.a.a.onMenuItemClick(Unknown Source:64)
 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:163)
 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:908)
 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:898)
 	at com.android.internal.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
 	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
 	at android.widget.AbsListView.performItemClick(AbsListView.java:1158)
 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3127)
 	at android.widget.AbsListView$3.run(AbsListView.java:4042)
 	at android.os.Handler.handleCallback(Handler.java:790)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:164)
 	at android.app.ActivityThread.main(ActivityThread.java:6499)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
```

**Comment by Butanediol** [comment]
[GitHub - CandyBar - Issue](https://github.com/danimahardhika/candybar-library/issues/118)
看起来其他图标包在自适应图标上也会有问题
